openapi: 3.0.0
info:
  version: 1.0.0
  title: Enrolment Service API
  description: This service handled client biometrics fingerprint enrolment
paths:
  /enrolments:
    get:
      description: Returns all enrolled clients
      tags: [ "Enrolments" ]
      operationId: "get"
      responses:
        "200":
          description: Successful response
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/SubjectList"
              examples:
                example:
                  value:
                    - id: "123e4567-e89b-12d3-a456-426614174000"
                      firstName: "John"
                      lastName: "Doe"
                      sex: "Male"
                      dateOfBirth: 1900-01-01
                    - id: "789e1234-e89b-12d3-a456-426614174111"
                      firstName: "Jane"
                      lastName: "Doe"
                      sex: "Female"
                      dateOfBirth: 1900-01-01

    post:
      description: Register a subject for biometric fingerprint verification
      tags: ["Enrolments"]
      operationId: "add"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Subject"
            examples:
              example:
                value:
                  firstName: "John"
                  lastName: "Doe"
                  sex: "Male"
                  dateOfBirth: 1900-01-01
                  sourceSubjectId: "000-000-000"
                  sourceSystem: "SmartCare"
                  fingerPrints:
                     - position: "LEFT_PINKY"
                       image: "base64encodedimage5"
                     - position: "RIGHT_PINKY"
                       image: "base64encodedimage6"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Subject"
              examples:
                example1:
                  value:
                    id: "123e4567-e89b-12d3-a456-426614174000"
                    firstName: "John"
                    lastName: "Doe"
                    sex: "Male"
                    sourceSubjectId: "000-000-000"
                    sourceSystem: "SmartCare"
                    fingerPrints:
                      - subjectId: "123e4567-e89b-12d3-a456-426614174000"
                        position: "LEFT_PINKY"
                        image: "base64encodedimage5"
                      - subjectId: "j123e4567-e89b-12d3-a456-426614174000"
                        position: "RIGHT_PINKY"
                        image: "base64encodedimage6"

  /enrolments/{id}:
    get:
      description: Returns a subject by id
      tags: [ "Enrolments" ]
      operationId: "getById"
      parameters:
        - name: id
          in: path
          required: true
          description: The subject id.
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Subject"
              examples:
                example:
                  value:
                    id: "123e4567-e89b-12d3-a456-426614174000"
                    firstName: "John"
                    lastName: "Doe"
                    sex: "Male"
                    sourceSubjectId: "000-000-000"
                    sourceSystem: "SmartCare"
                    fingerPrints:
                      - subjectId: "123e4567-e89b-12d3-a456-426614174000"
                        position: "LEFT_PINKY"
                        image: "base64encodedimage1"
                      - subjectId: "123e4567-e89b-12d3-a456-426614174000"
                        position: "RIGHT_PINKY"
                        image: "base64encodedimage2"
        "400":
          description: Specified subject ID is not a valid uuid
        "404":
          description: Post not found

    put:
      description: Update subject's basic information
      tags: ["Enrolments"]
      operationId: "update"
      parameters:
        - name: id
          in: path
          required: true
          description: The subject id
          schema:
            type: string
          examples:
            example:
              value:
                - id: "123e4567-e89b-12d3-a456-426614174000"
                  firstName: "John"
                  lastName: "Doe"
                  sex: "Male"
                  dateOfBirth: 1910-01-01

      responses:
        "204":
          description: Subject updated successfully
        "400":
          description: Specified subject ID is not a valid uuid

    delete:
      description: Delete enrolled subject
      tags: ["Enrolments"]
      operationId: "delete"
      parameters:
        - name: id
          in: path
          required: true
          description: The subject id
          schema:
            type: string
      responses:
        "204":
          description: Subject updated successfully
        "400":
          description: Specified subject ID is not a valid uuid

components:
  schemas:
    SubjectList:
      type: array
      items:
        $ref: "#/components/schemas/Subject"

    SourceSystemList:
      type: array
      items:
        $ref: "#/components/schemas/SourceSystem"

    SourceSystem:
      type: object
      required:
        - code
        - name
      properties:
        code:
          type: string
        name:
          type: string

    FingerprintData:
      type: object
      properties:
        subjectId:
          type: string
        position:
          type: string
        image:
          type: string
      required:
        - subjectId
        - position
        - image

    Subject:
      type: object
      required:
        - firstName
        - lastName
        - sex
        - sourceSubjectId
        - sourceSystem
      properties:
        id:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        sex:
          type: string
        sourceSubjectId:
          type: string
        sourceSystem:
          type: string
        fingerPrints:
          type: array
          items:
            $ref: "#/components/schemas/FingerprintData"

